#Database settings
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookhub_db?useSSL=false&serverTimezone=UTC
    username: bookhub_admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      #ddl-auto: update
  flyway:
    locations: classpath:db/migration,classpath:db/testdata




